ptscontrol: open_workspace: Add a default value for the copy parameter
Recently, a new `copy` parameter was added to the open_workspace
method, but not all usages were updated (tools). Add a default value
to this parameter to fix the exception:
TypeError: PyPTS.open_workspace() missing 1 required positional argument: 'copy'