iutctl: Add missing _btattach field initialization
In TTY mode, the _btattach field was not initialized and could cause
an exception at run_recovery() if active hub was used.
Fix the exception:
AttributeError: 'IutCtl' object has no attribute '_btattach'