client: Fix pts_addr_map crash
The autoptsclient-bluez.py fails to run with following error:

$ python3 ./autoptsclient-bluez.py "C:\Users\fdanis\Documents\Profile Tuning Suite\tests\tests.pqw6" --btpclient_path=/home/fdanis/src/bluez/client/btpclient/btpclient -i 192.168.1.48 -l 192.168.1.150 -c BAP
128711374763408 Starting PTS: 192.168.1.48:65000 ...
(128711374763408) OK
Traceback (most recent call last):
  File "/home/fdanis/src/auto-pts/./autoptsclient-bluez.py", line 40, in <module>
    main()
  File "/home/fdanis/src/auto-pts/./autoptsclient-bluez.py", line 36, in main
    client.start()
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1515, in start
    return self.main(args)
           ^^^^^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1561, in main
    stack.get_stack().pts_addr_map = self.args.pts_addr_map
                                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'pts_addr_map'

The 'pts_addr_map' was introduced by 1ea7a7cd9f9c9f13ce672ae489608b1cf6433c3f