bot: Fix TypeError
autoprojects.iutctl.init(args["kernel_image"], tty, args["board"])
TypeError: init() takes 1 positional argument but 3 were given

that occured after change in ptsproject/zephyr/iutctl.py:
def init(kernel_image, tty_file, board=None, use_rtt2pty=False))
to
def init(args)