generic wid: Fix AttributeError exception
If exception occured in generic wid handler, then in logs appears
exception like this
"
  File "C:\Users\User\auto-pts\autopts\ptsprojects\zephyr\bap_wid.py",
 line 31, in bap_wid_hdl
    handler = getattr(module, "hdl_wid_%d" % wid)
AttributeError: module 'autopts.ptsprojects.zephyr.bap_wid' has no
 attribute 'hdl_wid_20100'

During handling of the above exception, another exception occurred:

<traceback of a true cause of an exception>
"

This is a misleading log, that at first glance looks like it informs
about missing wid handler.