Removed extra termination of the QEMU process
QEMU process does not exist at this point, hence terminate throws exception:

OSError: [Errno 3] No such process