zephyr: Return of the support for single PTS dongle
This patch returns support for single PTS dongle, thus fixes regression:

Traceback (most recent call last):
  File "./autoptsclient-zephyr.py", line 183, in <module>
    main()
  File "./autoptsclient-zephyr.py", line 157, in main
    autoprojects.mesh.test_cases(ptses)
  File "/auto-pts/ptsprojects/zephyr/mesh.py", line 48, in test_cases
    pts2 = ptses[1]
IndexError: list index out of range

Multiple dongles are needed only for mesh tests.