btp: revert deletion of discover_and_verify
This fixes regression from ef6555a2b898780d1394f29e7db5920a8914ce2e where
discover_and_verify is removed. This causes error in Zephyr GAP since attribute
discover_and_verify is missing.

Traceback (most recent call last):
  File "./autoptsclient-zephyr.py", line 152, in <module>
    main()
  File "./autoptsclient-zephyr.py", line 126, in main
    test_cases = autoprojects.gap.test_cases(pts)
  File "/auto-pts/ptsprojects/zephyr/gap.py", line 170, in test_cases
    verify_wids={157: (btp.discover_and_verify, 'le', 'active',
AttributeError: 'module' object has no attribute 'discover_and_verify'