client: Fix logging an exception at exit
It seems that the 'code' field is specific for the SystemExit class, because
while handling other exception I've got this one:
  File "/home/codecoup/autopts/client.py", line 1378, in start
    if e.code != 0:
AttributeError: 'TimeoutError' object has no attribute 'code'